Parameters:
  SourceBucketName:
    Type: String
    Description: Name of the source S3 bucket that contains the files to copy

Resources:
  RawS3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      BucketName: 'datalake-raw-s3-mz'
    
  ProcessedS3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      BucketName: 'datalake-processed-s3-mz'
    
  TransformedS3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      BucketName: 'datalake-transformed-s3-mz'
     
  CopyLambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: copy-lambda-execution-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: copy-lambda-execution-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: 'arn:aws:logs:*:*:*'
              - Effect: Allow
                Action:
                  - 's3:ListBucket'
                  - 's3:GetObject'
                  - 's3:PutObject'
                Resource:
                  - !Sub 'arn:aws:s3:::${SourceBucketName}/*'
                  - !Sub 'arn:aws:s3:::${SourceBucketName}'
                  - !GetAtt RawS3Bucket.Arn
                  - !Sub '${RawS3Bucket.Arn}/*'

  CopyLambdaFunction:
    Type: 'AWS::Lambda::Function'
    DependsOn:
      - CopyLambdaExecutionRole
      - RawS3Bucket
    Properties:
      FunctionName: copy-lambda-function
      Handler: index.lambda_handler
      Role: !GetAtt CopyLambdaExecutionRole.Arn
      Environment:
        Variables:
          RawBucketName: !Ref RawS3Bucket
          SourceName: !Ref SourceBucketName
      Code:
        ZipFile: |
          import boto3
          import os
          
          s3 = boto3.client('s3')
          def lambda_handler(event, context):
              print(event)
              #to get source bucket name using environment variable
              source_bucket = os.environ['SourceName']
              
              #to get source bucket name from s3 notification event dictionary
              #source_bucket = event['Records'][0]['s3']['bucket']['name']
              
              print('source bucket is: {}.'.format(source_bucket))
              destination_bucket = os.environ['RawBucketName']
              
              #file name to be copied
              key = event['Records'][0]['s3']['object']['key']
              
              # Copy the object from source bucket to destination bucket
              s3.copy_object(Bucket=destination_bucket, CopySource={'Bucket': source_bucket, 'Key': key}, Key=key)
              
              return {
                  'statusCode': 200,
                  'body': 'File copied successfully'
              }
      Runtime: python3.9
      Timeout: 60
      MemorySize: 128

  CombineGlueJobRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: combine-glue-job-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: combine-glue-job-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:PutObject'
                Resource:
                  - !Sub 'arn:aws:s3:::${RawS3Bucket}'
                  - !Sub 'arn:aws:s3:::${RawS3Bucket}/*'
                  - !Sub 'arn:aws:s3:::${ProcessedS3Bucket}'
                  - !Sub 'arn:aws:s3:::${ProcessedS3Bucket}/*'

  CombineGlueJob:
    Type: 'AWS::Glue::Job'
    DependsOn:
      - CombineGlueJobRole
      - RawS3Bucket
      - ProcessedS3Bucket
    Properties:
      Name: combine-glue-job
      Role: !GetAtt CombineGlueJobRole.Arn
      Command:
        Name: pythonshell
        ScriptLocation: !Sub 's3://${RawS3Bucket}/combine_csv.py'

  TransformGlueJobRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: transform-glue-job-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "glue.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "GluePolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "s3:*"
                Resource: "arn:aws:s3:::*"
              - Effect: "Allow"
                Action: "glue:*"
                Resource: "*"

  TransformGlueJob:
    Type: 'AWS::Glue::Job'
    DependsOn:
      - TransformGlueJobRole
      - ProcessedS3Bucket
      - TransformedS3Bucket
    Properties:
      Name: transform-glue-job
      Role: !GetAtt TransformGlueJobRole.Arn
      Command:
        Name: pythonshell
        ScriptLocation: !Sub 's3://${ProcessedS3Bucket}/transform_to_parquet.py'